//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iStomaLab.Actualizari {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://licente.istoma.ro", ConfigurationName="Actualizari.ActualizariSoap")]
    public interface ActualizariSoap {
        
        // CODEGEN: Generating message contract since element name pCodClient from namespace http://licente.istoma.ro is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://licente.istoma.ro/GetDescriereVersiuneDisponibila", ReplyAction="*")]
        iStomaLab.Actualizari.GetDescriereVersiuneDisponibilaResponse GetDescriereVersiuneDisponibila(iStomaLab.Actualizari.GetDescriereVersiuneDisponibilaRequest request);
        
        // CODEGEN: Generating message contract since element name pCodClient from namespace http://licente.istoma.ro is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://licente.istoma.ro/ExistaActualizareDisponibila", ReplyAction="*")]
        iStomaLab.Actualizari.ExistaActualizareDisponibilaResponse ExistaActualizareDisponibila(iStomaLab.Actualizari.ExistaActualizareDisponibilaRequest request);
        
        // CODEGEN: Generating message contract since element name pCodClient from namespace http://licente.istoma.ro is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://licente.istoma.ro/SeteazaNouaVersiune", ReplyAction="*")]
        iStomaLab.Actualizari.SeteazaNouaVersiuneResponse SeteazaNouaVersiune(iStomaLab.Actualizari.SeteazaNouaVersiuneRequest request);
        
        // CODEGEN: Generating message contract since element name pCodClient from namespace http://licente.istoma.ro is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://licente.istoma.ro/GetVersiuneaUrmatoare", ReplyAction="*")]
        iStomaLab.Actualizari.GetVersiuneaUrmatoareResponse GetVersiuneaUrmatoare(iStomaLab.Actualizari.GetVersiuneaUrmatoareRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDescriereVersiuneDisponibilaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDescriereVersiuneDisponibila", Namespace="http://licente.istoma.ro", Order=0)]
        public iStomaLab.Actualizari.GetDescriereVersiuneDisponibilaRequestBody Body;
        
        public GetDescriereVersiuneDisponibilaRequest() {
        }
        
        public GetDescriereVersiuneDisponibilaRequest(iStomaLab.Actualizari.GetDescriereVersiuneDisponibilaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://licente.istoma.ro")]
    public partial class GetDescriereVersiuneDisponibilaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pCodClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pParolaClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pLicenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pIdStatie;
        
        public GetDescriereVersiuneDisponibilaRequestBody() {
        }
        
        public GetDescriereVersiuneDisponibilaRequestBody(string pCodClient, string pParolaClient, string pLicenta, string pIdStatie) {
            this.pCodClient = pCodClient;
            this.pParolaClient = pParolaClient;
            this.pLicenta = pLicenta;
            this.pIdStatie = pIdStatie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDescriereVersiuneDisponibilaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDescriereVersiuneDisponibilaResponse", Namespace="http://licente.istoma.ro", Order=0)]
        public iStomaLab.Actualizari.GetDescriereVersiuneDisponibilaResponseBody Body;
        
        public GetDescriereVersiuneDisponibilaResponse() {
        }
        
        public GetDescriereVersiuneDisponibilaResponse(iStomaLab.Actualizari.GetDescriereVersiuneDisponibilaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://licente.istoma.ro")]
    public partial class GetDescriereVersiuneDisponibilaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDescriereVersiuneDisponibilaResult;
        
        public GetDescriereVersiuneDisponibilaResponseBody() {
        }
        
        public GetDescriereVersiuneDisponibilaResponseBody(string GetDescriereVersiuneDisponibilaResult) {
            this.GetDescriereVersiuneDisponibilaResult = GetDescriereVersiuneDisponibilaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistaActualizareDisponibilaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistaActualizareDisponibila", Namespace="http://licente.istoma.ro", Order=0)]
        public iStomaLab.Actualizari.ExistaActualizareDisponibilaRequestBody Body;
        
        public ExistaActualizareDisponibilaRequest() {
        }
        
        public ExistaActualizareDisponibilaRequest(iStomaLab.Actualizari.ExistaActualizareDisponibilaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://licente.istoma.ro")]
    public partial class ExistaActualizareDisponibilaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pCodClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pParolaClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pLicenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pIdStatie;
        
        public ExistaActualizareDisponibilaRequestBody() {
        }
        
        public ExistaActualizareDisponibilaRequestBody(string pCodClient, string pParolaClient, string pLicenta, string pIdStatie) {
            this.pCodClient = pCodClient;
            this.pParolaClient = pParolaClient;
            this.pLicenta = pLicenta;
            this.pIdStatie = pIdStatie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistaActualizareDisponibilaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistaActualizareDisponibilaResponse", Namespace="http://licente.istoma.ro", Order=0)]
        public iStomaLab.Actualizari.ExistaActualizareDisponibilaResponseBody Body;
        
        public ExistaActualizareDisponibilaResponse() {
        }
        
        public ExistaActualizareDisponibilaResponse(iStomaLab.Actualizari.ExistaActualizareDisponibilaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://licente.istoma.ro")]
    public partial class ExistaActualizareDisponibilaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ExistaActualizareDisponibilaResult;
        
        public ExistaActualizareDisponibilaResponseBody() {
        }
        
        public ExistaActualizareDisponibilaResponseBody(bool ExistaActualizareDisponibilaResult) {
            this.ExistaActualizareDisponibilaResult = ExistaActualizareDisponibilaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeteazaNouaVersiuneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeteazaNouaVersiune", Namespace="http://licente.istoma.ro", Order=0)]
        public iStomaLab.Actualizari.SeteazaNouaVersiuneRequestBody Body;
        
        public SeteazaNouaVersiuneRequest() {
        }
        
        public SeteazaNouaVersiuneRequest(iStomaLab.Actualizari.SeteazaNouaVersiuneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://licente.istoma.ro")]
    public partial class SeteazaNouaVersiuneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pCodClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pParolaClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pLicenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pIdStatie;
        
        public SeteazaNouaVersiuneRequestBody() {
        }
        
        public SeteazaNouaVersiuneRequestBody(string pCodClient, string pParolaClient, string pLicenta, string pIdStatie) {
            this.pCodClient = pCodClient;
            this.pParolaClient = pParolaClient;
            this.pLicenta = pLicenta;
            this.pIdStatie = pIdStatie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeteazaNouaVersiuneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeteazaNouaVersiuneResponse", Namespace="http://licente.istoma.ro", Order=0)]
        public iStomaLab.Actualizari.SeteazaNouaVersiuneResponseBody Body;
        
        public SeteazaNouaVersiuneResponse() {
        }
        
        public SeteazaNouaVersiuneResponse(iStomaLab.Actualizari.SeteazaNouaVersiuneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SeteazaNouaVersiuneResponseBody {
        
        public SeteazaNouaVersiuneResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersiuneaUrmatoareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersiuneaUrmatoare", Namespace="http://licente.istoma.ro", Order=0)]
        public iStomaLab.Actualizari.GetVersiuneaUrmatoareRequestBody Body;
        
        public GetVersiuneaUrmatoareRequest() {
        }
        
        public GetVersiuneaUrmatoareRequest(iStomaLab.Actualizari.GetVersiuneaUrmatoareRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://licente.istoma.ro")]
    public partial class GetVersiuneaUrmatoareRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pCodClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pParolaClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pLicenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pIdStatie;
        
        public GetVersiuneaUrmatoareRequestBody() {
        }
        
        public GetVersiuneaUrmatoareRequestBody(string pCodClient, string pParolaClient, string pLicenta, string pIdStatie) {
            this.pCodClient = pCodClient;
            this.pParolaClient = pParolaClient;
            this.pLicenta = pLicenta;
            this.pIdStatie = pIdStatie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersiuneaUrmatoareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersiuneaUrmatoareResponse", Namespace="http://licente.istoma.ro", Order=0)]
        public iStomaLab.Actualizari.GetVersiuneaUrmatoareResponseBody Body;
        
        public GetVersiuneaUrmatoareResponse() {
        }
        
        public GetVersiuneaUrmatoareResponse(iStomaLab.Actualizari.GetVersiuneaUrmatoareResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://licente.istoma.ro")]
    public partial class GetVersiuneaUrmatoareResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetVersiuneaUrmatoareResult;
        
        public GetVersiuneaUrmatoareResponseBody() {
        }
        
        public GetVersiuneaUrmatoareResponseBody(byte[] GetVersiuneaUrmatoareResult) {
            this.GetVersiuneaUrmatoareResult = GetVersiuneaUrmatoareResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActualizariSoapChannel : iStomaLab.Actualizari.ActualizariSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActualizariSoapClient : System.ServiceModel.ClientBase<iStomaLab.Actualizari.ActualizariSoap>, iStomaLab.Actualizari.ActualizariSoap {
        
        public ActualizariSoapClient() {
        }
        
        public ActualizariSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActualizariSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActualizariSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActualizariSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iStomaLab.Actualizari.GetDescriereVersiuneDisponibilaResponse iStomaLab.Actualizari.ActualizariSoap.GetDescriereVersiuneDisponibila(iStomaLab.Actualizari.GetDescriereVersiuneDisponibilaRequest request) {
            return base.Channel.GetDescriereVersiuneDisponibila(request);
        }
        
        public string GetDescriereVersiuneDisponibila(string pCodClient, string pParolaClient, string pLicenta, string pIdStatie) {
            iStomaLab.Actualizari.GetDescriereVersiuneDisponibilaRequest inValue = new iStomaLab.Actualizari.GetDescriereVersiuneDisponibilaRequest();
            inValue.Body = new iStomaLab.Actualizari.GetDescriereVersiuneDisponibilaRequestBody();
            inValue.Body.pCodClient = pCodClient;
            inValue.Body.pParolaClient = pParolaClient;
            inValue.Body.pLicenta = pLicenta;
            inValue.Body.pIdStatie = pIdStatie;
            iStomaLab.Actualizari.GetDescriereVersiuneDisponibilaResponse retVal = ((iStomaLab.Actualizari.ActualizariSoap)(this)).GetDescriereVersiuneDisponibila(inValue);
            return retVal.Body.GetDescriereVersiuneDisponibilaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iStomaLab.Actualizari.ExistaActualizareDisponibilaResponse iStomaLab.Actualizari.ActualizariSoap.ExistaActualizareDisponibila(iStomaLab.Actualizari.ExistaActualizareDisponibilaRequest request) {
            return base.Channel.ExistaActualizareDisponibila(request);
        }
        
        public bool ExistaActualizareDisponibila(string pCodClient, string pParolaClient, string pLicenta, string pIdStatie) {
            iStomaLab.Actualizari.ExistaActualizareDisponibilaRequest inValue = new iStomaLab.Actualizari.ExistaActualizareDisponibilaRequest();
            inValue.Body = new iStomaLab.Actualizari.ExistaActualizareDisponibilaRequestBody();
            inValue.Body.pCodClient = pCodClient;
            inValue.Body.pParolaClient = pParolaClient;
            inValue.Body.pLicenta = pLicenta;
            inValue.Body.pIdStatie = pIdStatie;
            iStomaLab.Actualizari.ExistaActualizareDisponibilaResponse retVal = ((iStomaLab.Actualizari.ActualizariSoap)(this)).ExistaActualizareDisponibila(inValue);
            return retVal.Body.ExistaActualizareDisponibilaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iStomaLab.Actualizari.SeteazaNouaVersiuneResponse iStomaLab.Actualizari.ActualizariSoap.SeteazaNouaVersiune(iStomaLab.Actualizari.SeteazaNouaVersiuneRequest request) {
            return base.Channel.SeteazaNouaVersiune(request);
        }
        
        public void SeteazaNouaVersiune(string pCodClient, string pParolaClient, string pLicenta, string pIdStatie) {
            iStomaLab.Actualizari.SeteazaNouaVersiuneRequest inValue = new iStomaLab.Actualizari.SeteazaNouaVersiuneRequest();
            inValue.Body = new iStomaLab.Actualizari.SeteazaNouaVersiuneRequestBody();
            inValue.Body.pCodClient = pCodClient;
            inValue.Body.pParolaClient = pParolaClient;
            inValue.Body.pLicenta = pLicenta;
            inValue.Body.pIdStatie = pIdStatie;
            iStomaLab.Actualizari.SeteazaNouaVersiuneResponse retVal = ((iStomaLab.Actualizari.ActualizariSoap)(this)).SeteazaNouaVersiune(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iStomaLab.Actualizari.GetVersiuneaUrmatoareResponse iStomaLab.Actualizari.ActualizariSoap.GetVersiuneaUrmatoare(iStomaLab.Actualizari.GetVersiuneaUrmatoareRequest request) {
            return base.Channel.GetVersiuneaUrmatoare(request);
        }
        
        public byte[] GetVersiuneaUrmatoare(string pCodClient, string pParolaClient, string pLicenta, string pIdStatie) {
            iStomaLab.Actualizari.GetVersiuneaUrmatoareRequest inValue = new iStomaLab.Actualizari.GetVersiuneaUrmatoareRequest();
            inValue.Body = new iStomaLab.Actualizari.GetVersiuneaUrmatoareRequestBody();
            inValue.Body.pCodClient = pCodClient;
            inValue.Body.pParolaClient = pParolaClient;
            inValue.Body.pLicenta = pLicenta;
            inValue.Body.pIdStatie = pIdStatie;
            iStomaLab.Actualizari.GetVersiuneaUrmatoareResponse retVal = ((iStomaLab.Actualizari.ActualizariSoap)(this)).GetVersiuneaUrmatoare(inValue);
            return retVal.Body.GetVersiuneaUrmatoareResult;
        }
    }
}
