//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iStomaLab.iStatie {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://licente.istoma.ro", ConfigurationName="iStatie.ValidareStatieDeLucruSoap")]
    public interface ValidareStatieDeLucruSoap {
        
        // CODEGEN: Generating message contract since element name pCodClient from namespace http://licente.istoma.ro is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://licente.istoma.ro/VerificaStatia", ReplyAction="*")]
        iStomaLab.iStatie.VerificaStatiaResponse VerificaStatia(iStomaLab.iStatie.VerificaStatiaRequest request);
        
        // CODEGEN: Generating message contract since element name pCodClient from namespace http://licente.istoma.ro is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://licente.istoma.ro/VerificaStatiaV2", ReplyAction="*")]
        iStomaLab.iStatie.VerificaStatiaV2Response VerificaStatiaV2(iStomaLab.iStatie.VerificaStatiaV2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaStatiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaStatia", Namespace="http://licente.istoma.ro", Order=0)]
        public iStomaLab.iStatie.VerificaStatiaRequestBody Body;
        
        public VerificaStatiaRequest() {
        }
        
        public VerificaStatiaRequest(iStomaLab.iStatie.VerificaStatiaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://licente.istoma.ro")]
    public partial class VerificaStatiaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pCodClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pParolaClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pLicenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pIdStatie;
        
        public VerificaStatiaRequestBody() {
        }
        
        public VerificaStatiaRequestBody(string pCodClient, string pParolaClient, string pLicenta, string pIdStatie) {
            this.pCodClient = pCodClient;
            this.pParolaClient = pParolaClient;
            this.pLicenta = pLicenta;
            this.pIdStatie = pIdStatie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaStatiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaStatiaResponse", Namespace="http://licente.istoma.ro", Order=0)]
        public iStomaLab.iStatie.VerificaStatiaResponseBody Body;
        
        public VerificaStatiaResponse() {
        }
        
        public VerificaStatiaResponse(iStomaLab.iStatie.VerificaStatiaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://licente.istoma.ro")]
    public partial class VerificaStatiaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerificaStatiaResult;
        
        public VerificaStatiaResponseBody() {
        }
        
        public VerificaStatiaResponseBody(string VerificaStatiaResult) {
            this.VerificaStatiaResult = VerificaStatiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaStatiaV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaStatiaV2", Namespace="http://licente.istoma.ro", Order=0)]
        public iStomaLab.iStatie.VerificaStatiaV2RequestBody Body;
        
        public VerificaStatiaV2Request() {
        }
        
        public VerificaStatiaV2Request(iStomaLab.iStatie.VerificaStatiaV2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://licente.istoma.ro")]
    public partial class VerificaStatiaV2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pCodClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pParolaClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pLicenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pIdStatie;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pNumeStatie;
        
        public VerificaStatiaV2RequestBody() {
        }
        
        public VerificaStatiaV2RequestBody(string pCodClient, string pParolaClient, string pLicenta, string pIdStatie, string pNumeStatie) {
            this.pCodClient = pCodClient;
            this.pParolaClient = pParolaClient;
            this.pLicenta = pLicenta;
            this.pIdStatie = pIdStatie;
            this.pNumeStatie = pNumeStatie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaStatiaV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaStatiaV2Response", Namespace="http://licente.istoma.ro", Order=0)]
        public iStomaLab.iStatie.VerificaStatiaV2ResponseBody Body;
        
        public VerificaStatiaV2Response() {
        }
        
        public VerificaStatiaV2Response(iStomaLab.iStatie.VerificaStatiaV2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://licente.istoma.ro")]
    public partial class VerificaStatiaV2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerificaStatiaV2Result;
        
        public VerificaStatiaV2ResponseBody() {
        }
        
        public VerificaStatiaV2ResponseBody(string VerificaStatiaV2Result) {
            this.VerificaStatiaV2Result = VerificaStatiaV2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidareStatieDeLucruSoapChannel : iStomaLab.iStatie.ValidareStatieDeLucruSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidareStatieDeLucruSoapClient : System.ServiceModel.ClientBase<iStomaLab.iStatie.ValidareStatieDeLucruSoap>, iStomaLab.iStatie.ValidareStatieDeLucruSoap {
        
        public ValidareStatieDeLucruSoapClient() {
        }
        
        public ValidareStatieDeLucruSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidareStatieDeLucruSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidareStatieDeLucruSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidareStatieDeLucruSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iStomaLab.iStatie.VerificaStatiaResponse iStomaLab.iStatie.ValidareStatieDeLucruSoap.VerificaStatia(iStomaLab.iStatie.VerificaStatiaRequest request) {
            return base.Channel.VerificaStatia(request);
        }
        
        public string VerificaStatia(string pCodClient, string pParolaClient, string pLicenta, string pIdStatie) {
            iStomaLab.iStatie.VerificaStatiaRequest inValue = new iStomaLab.iStatie.VerificaStatiaRequest();
            inValue.Body = new iStomaLab.iStatie.VerificaStatiaRequestBody();
            inValue.Body.pCodClient = pCodClient;
            inValue.Body.pParolaClient = pParolaClient;
            inValue.Body.pLicenta = pLicenta;
            inValue.Body.pIdStatie = pIdStatie;
            iStomaLab.iStatie.VerificaStatiaResponse retVal = ((iStomaLab.iStatie.ValidareStatieDeLucruSoap)(this)).VerificaStatia(inValue);
            return retVal.Body.VerificaStatiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iStomaLab.iStatie.VerificaStatiaV2Response iStomaLab.iStatie.ValidareStatieDeLucruSoap.VerificaStatiaV2(iStomaLab.iStatie.VerificaStatiaV2Request request) {
            return base.Channel.VerificaStatiaV2(request);
        }
        
        public string VerificaStatiaV2(string pCodClient, string pParolaClient, string pLicenta, string pIdStatie, string pNumeStatie) {
            iStomaLab.iStatie.VerificaStatiaV2Request inValue = new iStomaLab.iStatie.VerificaStatiaV2Request();
            inValue.Body = new iStomaLab.iStatie.VerificaStatiaV2RequestBody();
            inValue.Body.pCodClient = pCodClient;
            inValue.Body.pParolaClient = pParolaClient;
            inValue.Body.pLicenta = pLicenta;
            inValue.Body.pIdStatie = pIdStatie;
            inValue.Body.pNumeStatie = pNumeStatie;
            iStomaLab.iStatie.VerificaStatiaV2Response retVal = ((iStomaLab.iStatie.ValidareStatieDeLucruSoap)(this)).VerificaStatiaV2(inValue);
            return retVal.Body.VerificaStatiaV2Result;
        }
    }
}
